### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by kurisubrooks** [hexenq/kuroshiro.js#1]
Here, we observe a simple Slack Bot before calling Kuroshiro:
![image](https://cloud.githubusercontent.com/assets/6291467/14588651/9651ade4-0511-11e6-9b60-e87f75dcce17.png)

And here we observe a simple Slack Bot after calling Kuroshiro:
![image](https://cloud.githubusercontent.com/assets/6291467/14588652/b3b3379a-0511-11e6-82f9-5e8f74610c69.png)

You can see my usage [here](https://github.com/kurisubrooks/nano/blob/master/commands/romaji.js). Any answers for why this may be happening, or how to fix this?

**Comment by hexenq** [comment]
Hi, kurisubrooks. Thanks for the feedback. I've checked this issue. It seems like the memory was taken by the initiation of kuromoji. Kuromoji initiates its tokenizer by extracting dictionary files to objects and mappings which may occupy quite a lot of memory. You could check the memory usage of [kuromoji.js](https://github.com/takuyaa/kuromoji.js), and about 200MB or more memory will be taken by initiating process. And I also work on finding out if there is a memory leak.
