### ISSUE TITLE
possible error assigning furigana/okurigana to words with more than one kanji (裏切る)

### ISSUE THREAD

**Issue by anime-scripts** [hexenq/kuroshiro.js#12]
When I call kuroshiro.convert with the following string:
  
  'フン ダルが 俺を裏切るとでも？'
  
using options = { mode : 'furigana' }, like this:
  
  kuroshiro.convert('フン ダルが 俺を裏切るとでも？',  { mode : 'furigana' } );
  
I get the response:
  
    "フン ダルが <ruby>俺<rp>(</rp><rt>おれ</rt><rp>)</rp></ruby>を<ruby>裏<rp>(</rp><rt>うらぎ</rt><rp>)</rp></ruby><ruby>切<rp>(</rp><rt></rt><rp>)</rp></ruby>るとでも？"

Which in a (modern) browser looks like:

   <span> フン ダルが <ruby>俺<rp>(</rp><rt>おれ</rt><rp>)</rp></ruby>を<ruby>裏<rp>(</rp><rt>うらぎ</rt><rp>)</rp></ruby><ruby>切<rp>(</rp><rt></rt><rp>)</rp></ruby>るとでも？</span>

  
The reading is correct, however the furigana is not assigned to the correct kanji. The 裏 in 裏切る should be assigned うる and the 切 should be assigned ぎ. Instead the 裏 is being assigned the entire reading of うらぎ and there is no furigana for 切:
  
Here is what the (relevant parts) of the result should look like:

    "<ruby>裏<rp>(</rp><rt>うら</rt><rp>)</rp></ruby><ruby>切<rp>(</rp><rt>ぎ</rt><rp>)</rp></ruby>"

Which should render correctly as:

<ruby>裏<rp>(</rp><rt>うら</rt><rp>)</rp></ruby><ruby>切<rp>(</rp><rt>ぎ</rt><rp>)</rp></ruby>

Alternatively, if the response was like this:

     "<ruby>裏切<rp>(</rp><rt>うらぎ</rt><rp>)</rp></ruby>"

It would show (correctly) in the browser as:

<ruby>裏切<rp>(</rp><rt>うらぎ</rt><rp>)</rp></ruby>

I can repeat this behavior using the online demo at http://www.hexenq.com/kuroshiro/demo/index.html when I enter the text フン ダルが 俺を裏切るとでも？ in the Original Text field, then select convert to 'Hiragana' with mode 'Furigana' and then hit the convert button.

It might be easier to see in the output of the online demo using the same input string but choosing mode 'Okurigana':

フン ダルが 俺(おれ)を裏(うらぎ)切()るとでも？

as you can see the () following the 切 is empty, and it's reading 'ぎ' has been assigned to 裏.

As always, thank you so much for developing this wonderful tool and continuing to support it, your project is enormously helpful to myself and I am sure many others.

** Edited to add, I am using  v 0.1.5 of kuroshiro

npm list kuroshiro
└── kuroshiro@0.1.5

**Comment by hexenq** [comment]
Hello, there. I've updated online demo to kuroshiro.js version 0.1.5 (It was 0.1.4 before). It should have been done with this issue. You can try on the demo site. I suggest you make a full re-installation of kuroshiro.js v0.1.5 and retry it. 
(P.S.: Both dictionary in path "dist/dict" and the library file are updated in version 0.1.5)
