### ISSUE TITLE
WanaKana dependency

### ISSUE THREAD

**Issue by DJTB** [hexenq/kuroshiro.js#13]
Hey there! 

Just giving you a heads up that I'll be publishing [2.0](https://github.com/WaniKani/WanaKana/tree/release-2.0) soon (pretty much a full rewrite), and should you choose to upgrade there might be some minor breaking changes (options object, punctuation conversion).

Feel free to take a look at the [tests](https://github.com/WaniKani/WanaKana/tree/release-2.0/src/__tests__) before updating!

**Comment by hexenq** [comment]
Hello, DJTB. Thanks for your work. I'll check the update soon : )

**Comment by hexenq** [comment]
Works done with f3a13c75b04be70b4a52e3f951e2a8e16ec8e384.
