### ISSUE TITLE
Browser kuroshiro.js "Tokenizer is null" 

### ISSUE THREAD

**Issue by Ayymoose** [hexenq/kuroshiro.js#23]
I'm trying to use the `kuroshiro.js` in `kuroshiro.js/dist` which is meant for browsers? But when I load the following HTML file:

```
<html>
<head>
  <meta charset="UTF-8">
</head>
<body>
  <script src="kuroshiro.js/dist/browser/kuroshiro.js"></script>
  <script>
	kuroshiro.init(function (err) {
		// kuroshiro is ready
		var result = kuroshiro.toHiragana('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！');    
		console.log(result);
	});
 </script>
</body>
</html>
```

I get an error from the console 

`TypeError: tokenizer is null` 
which brings me to 
Line 9171 
`var tokens = tokenizer.tokenize(str);`

Am I doing something wrong?

**Comment by hexenq** [comment]
It seems like that the dictionary was not found. I suggest you use the param `dicPath` to specify the path of the dictionary (e.g. 'kuroshiro.js/dist/dict') when calling `kuroshiro.init`.

**Comment by mornir** [comment]
I tried @hexenq solution and it works great.
