### ISSUE TITLE
Non-ideal results for terms that have kana in between kanji

### ISSUE THREAD

**Issue by mistval** [hexenq/kuroshiro.js#31]
Hello,

The following code reproduces this problem:

```js
const kuroshiro = require("kuroshiro");
kuroshiro.init(() => {
  console.log(kuroshiro.convert('言い分', {mode: 'furigana'}));
  console.log(kuroshiro.convert('言い訳', {mode: 'furigana'}));
});
```

It prints:

```
<ruby>言<rp>(</rp><rt></rt><rp>)</rp></ruby>い<ruby>分<rp>(</rp><rt>いぶん</rt><rp>)</rp></ruby>
<ruby>言<rp>(</rp><rt></rt><rp>)</rp></ruby>い<ruby>訳<rp>(</rp><rt>いわけ</rt><rp>)</rp></ruby>
```

All the furigana is on the second ruby, and nothing is on the first.

Thanks for the useful package, I'm depending on it here: https://www.npmjs.com/package/render-furigana :)

**Comment by hexenq** [comment]
Thanks for using kuroshiro. I've fixed the issue with the latest kuroshiro version 0.2.4. Hava try😄 You're welcome to raise another issue if needed. Closed.
