### ISSUE TITLE
calling kuroshiro from vuejs

### ISSUE THREAD

**Issue by subregi** [hexenq/kuroshiro.js#6]
Your npm package is really wonderful. I can build and use as a separate node application.
But when I wanted to integrate into my VueJS app, I encountered issues.
Isn't running npm install kuroshiro not enough?
I am using webpack and I am getting the following errors
Failed to load resource: the server responded with a status of 404 for the following two files:
bower_components/kuroshiro/dist/dict/base.dat.gz 
bower_components/kuroshiro/dist/dict/check.dat.gz
and whole bunch of errors caused by the above two files missing.

**Comment by hexenq** [comment]
Hello subregi, thanks for your feedback. By default, if you initiate kuroshiro without _options_ in the web environment, kuroshiro will look for IPA Dictionary files(like base.dat.gz, check.dat.gz, etc.) in this path - `bower_components/kuroshiro/dist/dict/`. If IPA Dictionary files doesn't exist in this path, it will come up with 404 errors. To handle this issue, try set `dicPath` (the relative path where the IPA Dictionary files are) explicitly when initiating kuroshiro, like this:
```
kuroshiro.init({
    dicPath: '/lib/kuroshiro/dict/'
}, function (err) {
    // kuroshiro.js is ready
    // do something
});
```

**Comment by subregi** [comment]
hello qi, thanks for this. It worked like a charm.
