### ISSUE TITLE
「サ」文字でコケてしまう件

### ISSUE THREAD

**Issue by mfargo** [hexenq/kuroshiro.js#7]
kuroshiro.isRomaji('サ')

throws an error from:
 kuroshiro/dist/node/kuroshiro.js:122:27

> var tokens = tokenizer.tokenize(str);
> TypeError: Cannot read property 'tokenize' of null

**Comment by hexenq** [comment]
Hello mfargo. Sorry for late response. Could you repeat this issue? The function "isRomaji" shouldn't go through the logic in line 122.

**Comment by hexenq** [comment]
Hello mfargo. kuroshiro.js has updated to 0.1.5. Have a try~ And If you still have some ideas or issues, feel free to raise them.
