### ISSUE TITLE
Calling bundle dict in vue js - laravel

### ISSUE THREAD

**Issue by onirusama** [hexenq/kuroshiro.js#8]
This package really powerfull, i want to use it in my current project. In my project i use vue js and laravel. But i have problem similar with [this issue](https://github.com/hexenq/kuroshiro.js/issues/6).  I see error in my console that say failed to load resource: the server responded with a status of 404 for file:
bower_components/kuroshiro/dist/dict/base.dat.gz
bower_components/kuroshiro/dist/dict/check.dat.gz
etc.

So i try with your answer from that issue, but this still not working and get same error. I set the dicPath like this:
```javascript
kuroshiro.init({
    // i see all of that require resource located in /node_modules/kuromoji/dict/
    dicPath: '/node_modules/kuromoji/dict/'
}, function (err) {
    var result = kuroshiro.convert('私は日本人です');
    console.log(result);
});
```
for more information i am also see error in my console like this:
```javascript
Uncaught TypeError: Cannot read property 'tokenize' of null
```

Sory, for bad english.

**Comment by hexenq** [comment]
Hello, onirusama. Sorry for this late response. First I must say I have little experience with vue.js and laravel. In my humble opinion, I think that the folder `/node_modules/kuromoji/dict/` might not be accessed from a builded vue project running under browser environment. I suggest you copy the dict folder to a static folder that your frontend logic can access. Then specify the dict path by setting `dicPath` when initiating kuroshiro. Hope this work for you.

**Comment by onirusama** [comment]
sory for late response. Thanks @hexenq . I copy `/node_modules/kuromoji/dict/` to my `/public` and this work now. :+1:
