### ISSUE TITLE
error when converting to hiragana with furigana mode 

### ISSUE THREAD

**Issue by anime-scripts** [hexenq/kuroshiro.js#9]
When I try and convert this string: ブラウン管への愛が足りねぇな

using kuroshiro.convert( 'ブラウン管への愛が足りねぇな', { mode: 'furigana'} ); I get the error message:

Uncaught TypeError: Cannot read property '1' of null at Object.convert

I can repeat this error using the online demo at http://www.hexenq.com/kuroshiro/demo/index.html when I enter the text ブラウン管への愛が足りねぇな in the Original Text field, then select convert to 'Hiragana' with mode 'Furigana' and then hit the convert button.

I thought it might be becuase the text has the halfwidth character 'ぇ' instead of 'え', but this turned out not to be the case.

 Other than this small issue, wonderful library, thanks for sharing!

**Comment by hexenq** [comment]
Hello. Thanks for your feedback. I checked this issue and found that there was a careless omission when handling katakana-kanji-mixed tokens. I fixed it with the latest version 0.1.4. Please update to it. Hope it will help :)
